---
resource_types:
  - name: google-cloud-storage
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
- name: pal-tracker
  type: git
  source:
    uri: git@github.com:xtreme-shane-lattanzio/pal-tracker.git
    branch: master
    private_key: {{github_ci_private_key}}
- name: pal-tracker-artifacts
  type: google-cloud-storage
  source:
    bucket: {{gcs-bucket}}
    regexp: releases/pal-tracker/pal-tracker-(.*).jar
    json_key: {{gcs-json}}
      
- name: version
  type: semver
  source:
    bucket: {{gcs-bucket}}
    endpoint: storage.googleapis.com
    key: pal-tracker/version
    access_key_id: {{gcs-access-key-id}}
    secret_access_key: {{gcs-secret-access-key}}

- name: review-deployment
  type: cf
  source:
    skip_cert_check: true
    api: https://api.sys.quandary.pal.pivotal.io
    username: {{deploy-username}}
    password: {{deploy-password}}
    organization: {{deploy-org}}
    space: {{review-space}}

- name: production-deployment
  type: cf
  source:
    skip_cert_check: true
    api: https://api.sys.quandary.pal.pivotal.io
    username: {{deploy-username}}
    password: {{deploy-password}}
    organization: {{deploy-org}}
    space: {{production-space}}

jobs:
- name: build
  plan:
  - get: pal-tracker
    trigger: true
  - get: version
    params: {bump: patch}
  - task: build and test
    file: pal-tracker/ci/tasks/build.yml
  - put: pal-tracker-artifacts
    params:
      file: build-output/pal-tracker-*.jar
  - put: version
    params:
      file: version/number

- name: deploy-review
  plan:
  - get: pal-tracker
  - get: pal-tracker-artifacts
    trigger: true
    passed: [build]
  - put: review-deployment
    params:
      manifest: pal-tracker/ci/deployments/manifest-review.yml
      path: pal-tracker-artifacts/pal-tracker-*.jar

- name: deploy-production
  plan:
  - get: pal-tracker
  - get: pal-tracker-artifacts
    passed: [deploy-review]
  - put: production-deployment
    params:
      manifest: pal-tracker/ci/deployments/manifest-production.yml
      path: pal-tracker-artifacts/pal-tracker-*.jar
