---
resources:
- name: pal-tracker
  type: git
  source:
    uri: TODO your github git@github.com:platform-acceleration-lab/pal-tracker.git
    branch: master
    private_key: {{github-private-key}}
- name: pal-tracker-artifacts
  type: s3
  source:
    bucket: {{aws-bucket}}
    regexp: releases/pal-tracker-(.*).jar
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
- name: version
  type: semver
  source:
    bucket: {{aws-bucket}}
    key: pal-tracker/version
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: review-deployment
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{deploy-username}}
    password: {{deploy-password}}
    organization: {{deploy-org}}
    space: {{review-space}}

- name: production-deployment
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{deploy-username}}
    password: {{deploy-password}}
    organization: {{deploy-org}}
    space: {{production-space}}

jobs:
- name: build
  plan:
  - get: pal-tracker
    trigger: true
  - get: version
    params: {bump: patch}
  - task: build and test
    file: pal-tracker/ci/tasks/build.yml
  - put: pal-tracker-artifacts
    params:
      file: build-output/pal-tracker-*.jar
  - put: version
    params:
      file: version/number

- name: deploy-review
  plan:
  - get: pal-tracker
  - get: pal-tracker-artifacts
    trigger: true
    passed: [build]
  - put: review-deployment
    params:
      manifest: pal-tracker/ci/deployments/manifest-review.yml
      path: pal-tracker-artifacts/pal-tracker-*.jar

- name: deploy-production
  plan:
  - get: pal-tracker
  - get: pal-tracker-artifacts
    passed: [deploy-review]
  - put: production-deployment
    params:
      manifest: pal-tracker/ci/deployments/manifest-production.yml
      path: pal-tracker-artifacts/pal-tracker-*.jar
